.scalenode-arm64-macos-settings: &scalenode-arm64-macos-settings
  image: macos://latest
  variables:
    SCALENODE_CPU: 4
    SCALENODE_DISK: 40
    SCALENODE_RAM: 4000
    SCALENODE_FEATURES: macos-aarch64

.ignore-bottle-updates: &ignore-bottle-updates
  except:
    variables:
       - $CI_COMMIT_TITLE =~ / update .* bottle/
       - $CI_COMMIT_TITLE =~ / add .* bottle/

.only_stable_changes: &only_stable_changes
  only:
    refs:
      - merge_requests
      - main
    changes:
      - .ci.yml
      - Formula/renode.rb

.only_nightly_changes: &only_nightly_changes
  only:
    refs:
      - merge_requests
      - main
    changes:
      - .ci.yml
      - Formula/renode-nightly.rb

.setup-tap: &setup-tap
  before_script:
    - brew tap renode/homebrew-renode $CI_REPOSITORY_URL
    - brew trust renode/homebrew-renode
    - pushd /opt/homebrew/Library/Taps/renode/homebrew-renode
    - git switch $CI_COMMIT_REF_NAME
    - popd

.setup-rosetta-tap: &setup-rosetta-tap
  before_script:
    - arch -x86_64 bash -c 'NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
    - eval "$(/usr/local/bin/brew shellenv)"
    - which brew
    - brew tap renode/homebrew-renode $CI_REPOSITORY_URL
    - brew trust renode/homebrew-renode
    - pushd /usr/local/Homebrew/Library/Taps/renode/homebrew-renode
    - git switch $CI_COMMIT_REF_NAME
    - popd

.build-bottle: &build-bottle |-
    brew install --build-bottle $FORMULA_NAME
    renode --version
    brew test $FORMULA_NAME
    brew bottle $FORMULA_NAME --root-url "builds.renode.io/brew" --json $FORMULA_NAME
    # Homebrew creates local files with $NAME--$VERSION but expects the uploaded files to be called $NAME-$VERSION (note the double vs single dash).
    # Both names are in the generated json file, so extract them from the json file and rename the bottle from .local_filename to .filename
    mv $(cat renode*.bottle.json | jq -r '.. | .local_filename? | select(. != null)') $(cat renode*.bottle.json | jq -r '.. | .filename? | select(. != null)')

stages:
  - build
  - deploy

arm64-macos-stable:
  stage: build
  dependencies: []
  <<: *scalenode-arm64-macos-settings
  <<: *ignore-bottle-updates
  <<: *only_stable_changes
  <<: *setup-tap
  script:
    - export FORMULA_NAME=renode
    - *build-bottle
  artifacts:
    paths:
        - renode*.json
        - renode*.tar.gz

x86-macos-stable:
  stage: build
  dependencies: []
  <<: *scalenode-arm64-macos-settings
  <<: *ignore-bottle-updates
  <<: *only_stable_changes
  <<: *setup-rosetta-tap
  script:
    - eval "$(/usr/local/bin/brew shellenv)"
    - export FORMULA_NAME=renode
    - *build-bottle
  artifacts:
    paths:
        - renode*.json
        - renode*.tar.gz
  retry: 2

arm64-macos-nightly:
  stage: build
  dependencies: []
  <<: *scalenode-arm64-macos-settings
  <<: *ignore-bottle-updates
  <<: *only_nightly_changes
  <<: *setup-tap
  script:
    - export FORMULA_NAME=renode-nightly
    - *build-bottle
  artifacts:
    paths:
        - renode*.json
        - renode*.tar.gz
x86-macos-nightly:
  stage: build
  dependencies: []
  <<: *scalenode-arm64-macos-settings
  <<: *ignore-bottle-updates
  <<: *only_nightly_changes
  <<: *setup-rosetta-tap
  script:
    - eval "$(/usr/local/bin/brew shellenv)"
    - export FORMULA_NAME=renode-nightly
    - *build-bottle
  artifacts:
    paths:
        - renode*.json
        - renode*.tar.gz
  retry: 2

publish:
  stage: deploy
  <<: *scalenode-arm64-macos-settings
  <<: *ignore-bottle-updates
  only:
    refs:
      - main
  <<: *setup-tap
  script:
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - git config --global user.email "HomebrewBot@renode"
    - git config --global user.name "Homebrew Bot"
    - brew bottle --write --merge renode*.json
    - eval $(ssh-agent -s)
    - echo "$RENODE_DL_KEY" > key
    - chmod 0400 key
    - ssh-add key
    - echo "$RENODE_DL_TARGET_DIR"
    - scp renode*.tar.gz "${RENODE_DL_USER}"@"${RENODE_DL_HOST}":"${RENODE_DL_TARGET_DIR}"
    - pushd /opt/homebrew/Library/Taps/renode/homebrew-renode
    - git show origin..HEAD
    - git push
    - popd
